name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd /home/ubuntu/test-cicd/_work/test-ci-cd/test-ci-cd/backend
    - run: npm ci
    - run: npm install npm@latest -g
    - run: npm install
    - run: cd ../frontend/
    - run: npm ci
    - run: npm install



  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: cd /home/ubuntu/test-cicd/_work/test-ci-cd/test-ci-cd/backend
      run: npm install
      run: cd ../frontend/
      run: npm install

    - name: Deploy to Cloud
      run: |
        cd /home/ubuntu/test-cicd/_work/test-ci-cd/test-ci-cd
        git pull origin main
        cd /backend/
        npm install
        cd ../frontend/
        npm install
        pm2 restart backend &
